services:
  - docker
language: php
php:
  - '7.2'
  - '7.3'
before_script:
  - composer install
  - cp .env.example .env
  - docker-compose -f docker-compose.dev.yml up -d --build
script: vendor/bin/phpunit
