version: '3.0'
services:
  rbb_db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: zd09d7r39406d7s869f5s
  rbb_db_pma:
    image: phpmyadmin/phpmyadmin:latest
    links:
     - rbb_db:db
    ports:
    - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: zd09d7r39406d7s869f5s
      PMA_USER: root
      PMA_PASSWORD: zd09d7r39406d7s869f5s
  rbb_www:
    depends_on:
    - rbb_db
    image: wordpress:latest
    volumes:
    - ".:/var/www/html/wp-content/plugins/kebabble"
    ports:
    - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: rbb_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: zd09d7r39406d7s869f5s
      WORDPRESS_DB_NAME: wp_kebabble
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        @ini_set('display_errors', 0);
