version: '3.6'
services:
  rbb_db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: zd09d7r39406d7s869f5s
  rbb_www:
    depends_on:
    - rbb_db
    image: wordpress:latest
    volumes:
    - ".:/var/www/html/wp-content/plugins/kebabble"
    ports:
    - 55556:80
    environment:
      WORDPRESS_DB_HOST: rbb_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: zd09d7r39406d7s869f5s
      WORDPRESS_DB_NAME: wp_kebabble
      WORDPRESS_DEBUG: 1