version: '3.6'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: zd09d7r39406d7s869f5s
  db_pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: zd09d7r39406d7s869f5s
      PMA_USER: root
      PMA_PASSWORD: zd09d7r39406d7s869f5s
  www:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ".:/var/www/html/wp-content/plugins/kebabble"
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: zd09d7r39406d7s869f5s
      WORDPRESS_DB_NAME: wp_kebabble
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', "http://{$_SERVER['SERVER_NAME']}/");
        define('WP_SITEURL', "http://{$_SERVER['SERVER_NAME']}/");
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        @ini_set('display_errors', 0);
